title: Michelle Leach, PhD
author: Michelle Leach
email: mkleach@umich.edu
description: > # this means to ignore newlines until "baseurl:"
  Resume and portfolio of Michelle Leach.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
